package com.example.monpremiersite.dto;

import com.example.monpremiersite.entities.LegalDeadline;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;

public class LegalDeadlineDTO {
    public Long id;
    public Long caseId;
    public String caseNumber;
    public String type;
    public String description;
    public LocalDate deadlineDate;
    public String statut;
    public Boolean autoGenerated;
    public Long sourceEventId;
    public long daysRemaining;
    public Integer remindersSent;
    public LocalDateTime createdAt;

    public static LegalDeadlineDTO fromEntity(LegalDeadline d) {
        LegalDeadlineDTO dto = new LegalDeadlineDTO();
        dto.id = d.getId();
        dto.type = d.getType() != null ? d.getType().name() : null;
        dto.description = d.getDescription();
        dto.deadlineDate = d.getDeadlineDate();
        dto.statut = d.getStatut() != null ? d.getStatut().name() : null;
        dto.autoGenerated = d.getAutoGenerated();
        dto.sourceEventId = d.getSourceEventId();
        dto.remindersSent = d.getRemindersSent();
        dto.createdAt = d.getCreatedAt();
        dto.daysRemaining = d.getDeadlineDate() != null
            ? ChronoUnit.DAYS.between(LocalDate.now(), d.getDeadlineDate())
            : 0;
        if (d.getCaseEntity() != null) {
            dto.caseId = d.getCaseEntity().getIdc();
            dto.caseNumber = d.getCaseEntity().getCase_number();
        }
        return dto;
    }
}
