INSERT IGNORE INTO roles (role_name) VALUES ('ADMINISTRATEUR');
INSERT IGNORE INTO roles (role_name) VALUES ('SECRETAIRE');
INSERT IGNORE INTO roles (role_name) VALUES ('AVOCAT');
INSERT IGNORE INTO roles (role_name) VALUES ('STAGIAIRE');
INSERT IGNORE INTO roles (role_name) VALUES ('CLIENT');
