package com.example.monpremiersite.entities;

import jakarta.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Table(name = "legal_deadlines")
public class LegalDeadline {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "case_id", nullable = false)
    private CaseEntity caseEntity;

    @Enumerated(EnumType.STRING)
    private DeadlineType type;

    @Column(columnDefinition = "TEXT")
    private String description;

    @Column(name = "deadline_date", nullable = false)
    private LocalDate deadlineDate;

    @Enumerated(EnumType.STRING)
    private DeadlineStatus statut = DeadlineStatus.EN_COURS;

    @Column(name = "auto_generated")
    private Boolean autoGenerated = false;

    @Column(name = "source_event_id")
    private Long sourceEventId;

    @Column(name = "reminders_sent")
    private Integer remindersSent = 0;

    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) createdAt = LocalDateTime.now();
        if (statut == null) statut = DeadlineStatus.EN_COURS;
        if (autoGenerated == null) autoGenerated = false;
        if (remindersSent == null) remindersSent = 0;
    }

    // ── Getters / Setters ────────────────────────────────────────────────────

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }

    public CaseEntity getCaseEntity() { return caseEntity; }
    public void setCaseEntity(CaseEntity caseEntity) { this.caseEntity = caseEntity; }

    public DeadlineType getType() { return type; }
    public void setType(DeadlineType type) { this.type = type; }

    public String getDescription() { return description; }
    public void setDescription(String description) { this.description = description; }

    public LocalDate getDeadlineDate() { return deadlineDate; }
    public void setDeadlineDate(LocalDate deadlineDate) { this.deadlineDate = deadlineDate; }

    public DeadlineStatus getStatut() { return statut; }
    public void setStatut(DeadlineStatus statut) { this.statut = statut; }

    public Boolean getAutoGenerated() { return autoGenerated; }
    public void setAutoGenerated(Boolean autoGenerated) { this.autoGenerated = autoGenerated; }

    public Long getSourceEventId() { return sourceEventId; }
    public void setSourceEventId(Long sourceEventId) { this.sourceEventId = sourceEventId; }

    public Integer getRemindersSent() { return remindersSent; }
    public void setRemindersSent(Integer remindersSent) { this.remindersSent = remindersSent; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
}
